////
Increasing Docker Storage

Module included in the following assemblies:

* day_two_guide/docker_tasks.adoc
////

Increasing the size of a volume used to store container images
may be required to ensure continued deployment without any outages.
In order to increase the amount of storage available, a free partition must be
made available that contains an appropriate amount of free capacity. The OpenShift
environment needs to have enough capacity to host the pods that are currently running on
the node requiring the storage because the pods must be evacuated from that node.

==== Evacuating the Node

The evacuation of a node is done from a master instance or an account
that is designated as a `cluster-admin` that can perform privileged tasks that
allow the evacuation of any pod from the node and disables scheduling of other
pods on that node.

[subs=+quotes]
----
$ NODE=*ose-app-node01.example.com*
$ oc adm manage-node ${NODE} --schedulable=false
NAME                          STATUS                     AGE       VERSION
ose-app-node01.example.com   Ready,SchedulingDisabled   20m       v1.6.1+5115d708d7

$ oc adm drain ${NODE} --ignore-daemonsets
node "ose-app-node01.example.com" already cordoned
pod "perl-1-build" evicted
pod "perl-1-3lnsh" evicted
pod "perl-1-9jzd8" evicted
node "ose-app-node01.example.com" drained
----

NOTE: If there are containers running with local volumes that won't migrate,
run the following command:
`oc adm drain ${NODE} --ignore-daemonsets --delete-local-data`

[subs=+quotes]
----
$ *oc adm manage-node ${NODE} --list-pods*

Listing matched pods on node: ose-app-node01.example.com

NAME      READY     STATUS    RESTARTS   AGE
----

NOTE: For more information on evacuating and draining pods or nodes, see
<<node_maintenance>>.

==== Increasing Storage with a New Disk

The following directions assume that a new disk has been added and is available
to the existing instance that required additional storage.

NOTE: The process may be differ depending on the underlying infrastructure
that is running {rhocp}.

The examples below assume the original disk is labeled `/dev/xvdb` and the
new disk is labeled `/dev/xvdd`.

[subs=+quotes]
----
# *vi /etc/sysconfig/docker-storage-setup*
DEVS="/dev/xvdb /dev/xvdd"
..omitted..
----

Stop the `docker` and the `atomic-openshift-node` services and run the
`docker-storage-setup` command in order to extend the volume groups and
logical volumes associated with container storage.

[subs=+quotes]
----
# *systemctl stop docker atomic-openshift-node*
# *docker-storage-setup*
INFO: Volume group backing root filesystem could not be determined
INFO: Device /dev/xvdb is already partitioned and is part of volume group docker_vol
INFO: Device node /dev/xvdd1 exists.
  Physical volume "/dev/xvdd1" successfully created.
  Volume group "docker_vol" successfully extended

# *systemctl start docker*
# *vgs*
  VG         #PV #LV #SN Attr   VSize  VFree
  docker_vol   2   1   0 wz--n- 64.99g <55.00g
----

A benefit in adding a disk compared to creating a new volume group and
re-running `docker-storage-setup` is that the images that were used on the system
still exist after the new storage has been added.

[subs=+quotes]
----
# docker images
REPOSITORY                                              TAG                 IMAGE ID            CREATED             SIZE
docker-registry.default.svc:5000/tet/perl               latest              8b0b0106fb5e        13 minutes ago      627.4 MB
registry.access.redhat.com/rhscl/perl-524-rhel7         <none>              912b01ac7570        6 days ago          559.5 MB
registry.access.redhat.com/openshift3/ose-deployer      v3.6.173.0.21       89fd398a337d        5 weeks ago         970.2 MB
registry.access.redhat.com/openshift3/ose-sti-builder   v3.6.173.0.21       99ab8895d88a        5 weeks ago         970.2 MB
registry.access.redhat.com/openshift3/ose-pod           v3.6.173.0.21       63accd48a0d7        5 weeks ago         208.6 MB
----

==== Making the Node Ready

With the increase in storage capacity, the final step is to enable the node to
be schedulable in order to accept new incoming pods. From a master instance or
an account that is designated as a `cluster-admin` that can perform privileged
tasks, perform the following command:

[subs=+quotes]
----
$ oc adm manage-node ${NODE} --schedulable=true

ose-master01.example.com   Ready,SchedulingDisabled   24m       v1.6.1+5115d708d7
ose-master02.example.com   Ready,SchedulingDisabled   24m       v1.6.1+5115d708d7
ose-master03.example.com   Ready,SchedulingDisabled   24m       v1.6.1+5115d708d7
ose-infra-node01.example.com   Ready                      24m       v1.6.1+5115d708d7
ose-infra-node02.example.com   Ready                      24m       v1.6.1+5115d708d7
ose-infra-node03.example.com   Ready                      24m       v1.6.1+5115d708d7
ose-app-node01.example.com   Ready                      24m       v1.6.1+5115d708d7
ose-app-node02.example.com   Ready                      24m       v1.6.1+5115d708d7
----

=== Changing the Storage Back-end

With the advancements of services and file systems, changes in a current storage
back-end may be necessary to take advantage of features not available with the
current setup. The following steps provide an example of changing a device mapper
back-end to an `overlay2` storage back-end. `overlay2` offers increased speed and
density over traditional device mapper.


==== Evacuating the Node

From a master instance or an account that is designated as a `cluster-admin`,
perform the following tasks to evacuate any pods from the node and disable
scheduling.

[subs=+quotes]
----
$ *NODE=ose-app-node01.example.com*
$ *oc adm manage-node ${NODE} --schedulable=false*
NAME                          STATUS                     AGE       VERSION
ose-app-node01.example.com   Ready,SchedulingDisabled   20m       v1.6.1+5115d708d7

$ *oc adm drain ${NODE} --ignore-daemonsets*
node "ose-app-node01.example.com" already cordoned
pod "perl-1-build" evicted
pod "perl-1-3lnsh" evicted
pod "perl-1-9jzd8" evicted
node "ose-app-node01.example.com" drained
----

NOTE: If there are containers running with local volumes that will not migrate run the following command.
`oc adm drain ${NODE} --ignore-daemonsets --delete-local-data`

[subs=+quotes]
----
$ *oc adm manage-node ${NODE} --list-pods*

Listing matched pods on node: ose-app-node01.example.com

NAME      READY     STATUS    RESTARTS   AGE
----

NOTE: For more information on evacuating and draining pods or nodes, see
<<node_maintenance>>.

==== Modifying the Back-end Storage

The steps below stop the `docker` service, modify the current partition(s), and
start the `docker` service. During this time, any images that currently exist
on the system need to be pulled again from the registry.

With no containers currently running on the instance,
stop the `docker` and `atomic-openshift-node service.

[subs=+quotes]
----
# *systemctl stop docker atomic-openshift-node*
----

Verify the name of the volume group, logical volume name, and physical volume
name.

[subs=+quotes]
----
# vgs
  VG         #PV #LV #SN Attr   VSize   VFree
  docker_vol   1   1   0 wz--n- <25.00g 15.00g

# lvs
LV       VG         Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
 dockerlv docker_vol -wi-ao---- <10.00g

# lvremove /dev/docker_vol/docker-pool  -y
# vgremove docker_vol -y
# pvs
  PV         VG         Fmt  Attr PSize   PFree
  /dev/xvdb1 docker_vol lvm2 a--  <25.00g 15.00g

# pvremove /dev/xvdb1 -y
# rm -Rf /var/lib/docker/*
# rm -f /etc/sysconfig/docker-storage
----

Modify the `docker-storage-setup` file to specify the `STORAGE_DRIVER`.

NOTE: When a system is upgrade from {rhel} 7.3 to
{rhel} 7.4 the `docker` service attempts to use `/var` with the `STORAGE_DRIVER`
of extfs. The use of extfs as the `STORAGE_DRIVER` causes errors in {rhocp}.
More info regarding the error can be found on the https://bugzilla.redhat.com/show_bug.cgi?id=1490910[Bugzilla ID: 1490910]

[subs=+quotes]
----
DEVS=/dev/xvdb
VG=docker_vol
DATA_SIZE=95%VG
STORAGE_DRIVER=overlay2
CONTAINER_ROOT_LV_NAME=dockerlv
CONTAINER_ROOT_LV_MOUNT_PATH=/var/lib/docker
CONTAINER_ROOT_LV_SIZE=100%FREE
----

Set up the storage by running the `docker-storage-setup` command and then start
the `docker` and `atomic-openshift-node` services.

[subs=+quotes]
----
# docker-storage-setup
# systemctl start docker atomic-openshift-node
----

==== Making the Node Ready

With the storage modified to use `overlay2`, the final step is to enable the
node to be schedulable in order to accept new incoming pods. From a master
instance or an account that is designated as a `cluster-admin` that can perform
privileged tasks, perform the following command:

[subs=+quotes]
----
$ oc adm manage-node ${NODE} --schedulable=true

ose-master01.example.com   Ready,SchedulingDisabled   24m       v1.6.1+5115d708d7
ose-master02.example.com   Ready,SchedulingDisabled   24m       v1.6.1+5115d708d7
ose-master03.example.com   Ready,SchedulingDisabled   24m       v1.6.1+5115d708d7
ose-infra-node01.example.com   Ready                      24m       v1.6.1+5115d708d7
ose-infra-node02.example.com   Ready                      24m       v1.6.1+5115d708d7
ose-infra-node03.example.com   Ready                      24m       v1.6.1+5115d708d7
ose-app-node01.example.com   Ready                      24m       v1.6.1+5115d708d7
ose-app-node02.example.com   Ready                      24m       v1.6.1+5115d708d7
----

NOTE: For more information on evacuating and draining pods or nodes, see
<<node_maintenance>>.

////
=== Docker Backup
The Docker daemon uses different configuration files stored in the
`/etc/sysconfig` directory:

* `/etc/sysconfig/docker`
* `/etc/sysconfig/docker-network`
* `/etc/sysconfig/docker-storage`
* `/etc/sysconfig/docker-storage-setup`

NOTE: `/etc/sysconfig/docker-storage-setup` is used to create the Docker storage
and it creates the `/etc/sysconfig/docker-storage` file, so even if it is not
critical, it can be helpful to backup as well.

This snippet can be used:

----
$ tar -czvf docker-config-$(hostname)-$(date +%Y%m%d).tar.gz /etc/sysconfig/docker*
----
////