////
Creating a node host backup

Module included in the following assemblies:

* day_two_guide/host_level_tasks.adoc
////

The backup process is to be performed before any change to the infrastructure
such as a system update, upgrade, or any other significant modification.
It is to be performed on regular basis to ensure a proper backup is
available if a failure occurs.

*{rhocp} related files*

The node instances run the applications in form of `pods` based on containers.
The configuration of the node services, certificates generated by the
installation, cloud provider related configuration, keys and some other files
such as part of the `dnsmasq` configuration are stored in the
`/etc/origin/` and `/etc/origin/node` directories.

The {rhocp} services can be customized to increase the log level, use proxies,
etc. and the configuration files are stored in the `/etc/sysconfig` directory.

To create a backup of the {rhocp} node configuration files, the following
snippet can be used:

[subs=+quotes]
----
$ MYBACKUPDIR=/backup/$(hostname)/$(date +%Y%m%d)
$ sudo mkdir -p ${MYBACKUPDIR}/etc/sysconfig
$ sudo cp -aR /etc/origin ${MYBACKUPDIR}/etc
$ sudo cp -aR /etc/sysconfig/atomic-openshift-node ${MYBACKUPDIR}/etc/sysconfig/
----

*Other important files*

There are some other files {rhocp} uses that must be taken into account
when planning the backup policy, including:

|===
^|File ^|Description
|`/etc/cni/*` |Container Network Interface configuration (if used)
| `/etc/sysconfig/iptables` |Where the `iptables` rules are stored
| `/etc/sysconfig/docker-storage-setup` |The input file for `container-storage-setup` command
| `/etc/sysconfig/docker` |The `docker` configuration file
| `/etc/sysconfig/docker-network` |`docker` networking configuration (i.e. MTU)
| `/etc/sysconfig/docker-storage` |`docker` storage configuration (generated by `container-storage-setup`)
| `/etc/dnsmasq.conf` |Main configuration file for `dnsmasq`
| `/etc/dnsmasq.d/*` |Different `dnsmasq` configuration files
| `/etc/sysconfig/flanneld` |`flannel` configuration file (if used)
| `/etc/pki/ca-trust/source/anchors/` |Certificates added to the system (i.e. for external registries)
|===

To create those files:

----
$ MYBACKUPDIR=/backup/$(hostname)/$(date +%Y%m%d)
$ sudo mkdir -p ${MYBACKUPDIR}/etc/sysconfig
$ sudo mkdir -p ${MYBACKUPDIR}/etc/pki/ca-trust/source/anchors
$ sudo cp -aR /etc/sysconfig/{iptables,docker-*,flanneld} \
    ${MYBACKUPDIR}/etc/sysconfig/
$ sudo cp -aR /etc/dnsmasq* /etc/cni ${MYBACKUPDIR}/etc/
$ sudo cp -aR /etc/pki/ca-trust/source/anchors/* \
    ${MYBACKUPDIR}/etc/pki/ca-trust/source/anchors/
----

*{rhel} packages*

In the event of accidentally removing a package or a file included in a `rpm`
package must be restored, having a list of {rhel} packages installed in the
system can be useful.

NOTE: If using {rh} Satellite features such as content views or the facts store
provide a proper mechanism to reinstall the missing packages and a historical
data of packages installed in the systems.

To create a list of the current {rhel} packages installed in the system:

[subs=+quotes]
----
$ MYBACKUPDIR=/backup/$(hostname)/$(date +%Y%m%d)
$ sudo mkdir -p ${MYBACKUPDIR}
$ rpm -qa | sort | sudo tee $MYBACKUPDIR/packages.txt
----

*Files structure*

If using the previous snippets, the following files must be present in the
backup directory:

[subs=+quotes]
----
$ MYBACKUPDIR=*/backup/$(hostname)/$(date +%Y%m%d)*
$ sudo find ${MYBACKUPDIR} -mindepth 1 -type f -printf '%P\n'
etc/sysconfig/atomic-openshift-node
etc/sysconfig/flanneld
etc/sysconfig/iptables
etc/sysconfig/docker-network
etc/sysconfig/docker-storage
etc/sysconfig/docker-storage-setup
etc/sysconfig/docker-storage-setup.rpmnew
etc/origin/node/system:node:app-node-0.example.com.crt
etc/origin/node/system:node:app-node-0.example.com.key
etc/origin/node/ca.crt
etc/origin/node/system:node:app-node-0.example.com.kubeconfig
etc/origin/node/server.crt
etc/origin/node/server.key
etc/origin/node/node-dnsmasq.conf
etc/origin/node/resolv.conf
etc/origin/node/node-config.yaml
etc/origin/node/flannel.etcd-client.key
etc/origin/node/flannel.etcd-client.csr
etc/origin/node/flannel.etcd-client.crt
etc/origin/node/flannel.etcd-ca.crt
etc/origin/cloudprovider/openstack.conf
etc/pki/ca-trust/source/anchors/openshift-ca.crt
etc/pki/ca-trust/source/anchors/registry-ca.crt
etc/dnsmasq.conf
etc/dnsmasq.d/origin-dns.conf
etc/dnsmasq.d/origin-upstream-dns.conf
etc/dnsmasq.d/node-dnsmasq.conf
packages.txt
----

If required, the files can be compressed to save some space as:

[subs=+quotes]
----
$ MYBACKUPDIR=*/backup/$(hostname)/$(date +%Y%m%d)*
$ sudo tar -zcvf */backup/*$(hostname)-$(date +%Y%m%d).tar.gz $MYBACKUPDIR
$ sudo rm -Rf ${MYBACKUPDIR}
----

To easily create those files, the `openshift-ansible-contrib` repository
contains a script `backup_master_node.sh` that performs the previous steps. The
script creates a directory on the host running the script and copies all the
files previously mentioned.

NOTE: The code in the `openshift-ansible-contrib` repository referenced below
is not explicitly supported by Red Hat but the Reference Architecture team
performs testing to ensure the code operates as defined and is secure.

The script is to be executed on every master host as:

[subs=+quotes]
----
$ mkdir ~/git
$ cd ~/git
$ git clone https://github.com/openshift/openshift-ansible-contrib.git
$ cd openshift-ansible-contrib/reference-architecture/day2ops/scripts
$ ./backup_master_node.sh -h
----